"""Added cascade behavior for the **User** and **Pet** models

Revision ID: 3ace290d61b0
Revises: 108a3af75cb2
Create Date: 2025-12-14 21:11:39.390828

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3ace290d61b0"
down_revision: Union[str, Sequence[str], None] = "108a3af75cb2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
