"""Changing the name column

Revision ID: 8110a73c9995
Revises: 42ddfae08683
Create Date: 2025-12-13 12:54:09.796427

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8110a73c9995"
down_revision: Union[str, Sequence[str], None] = "42ddfae08683"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("username", sa.String(length=50), nullable=False))
    op.drop_column("users", "name")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("name", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    )
    op.drop_column("users", "username")
    # ### end Alembic commands ###
